### ISSUE TITLE
Nullreference exception with some markdown

### ISSUE THREAD

**Issue by ogchrislem** [wbaldoumas/markdown-colorcode#88] opened 2023-05-24 12:05 UTC
## Description

"System.NullReferenceException: Object reference not set to an instance of an object" thrown with some markdown, only when colorcode extension is used

## Expected Behaviour

No error is thrown and markdown is produced

## Actual Behaviour

Error was thrown

## Affected Version

1.0.3

## Steps to Reproduce

Sample code

```
using Markdig;
using Markdown.ColorCode;
using ColorCode.Styling;
using System;

public class Program
{
	public static void Main()
	{
		
		var markdownPipeline = new Markdig.MarkdownPipelineBuilder()
            .UsePipeTables()
            .UseAdvancedExtensions()
            .UseColorCode(StyleDictionary.DefaultDark)
            .UseAutoLinks()
            .UseEmojiAndSmiley()
            .UseMediaLinks()
            .UseCitations()
            .Build();
		
		var result = Markdig.Markdown.ToHtml("To print \"Hello World\" in C#, you can use the following code:\n```c",markdownPipeline);
		Console.WriteLine(result); 
	}
}
```
Error is not thrown if UseColorCode line is commented out

## Checklist

- [x] I have read the [contributing guidelines](https://github.com/wbaldoumas/markdown-colorcode/blob/main/CONTRIBUTING.md)
- [x] I have verified this does not duplicate an existing issue

**Comment by ogchrislem** [comment] 2023-05-24 13:37
On investigating further it's something to do with the language name after the backticks. Adding a newline character on the string to be formatted still produces the error, but adding a newline followed by at least one other character works.

**Comment by wbaldoumas** [comment] 2023-05-24 16:19
Thanks for the details, @ogchrislem!

I will start looking into this as I have time, but you can also feel free to open a pull request if you've found the problem and would like to address this issue yourself.

**Comment by wbaldoumas** [comment] 2023-05-25 00:17
@ogchrislem I'm able to replicate your issue and see what the problem is. 

You aren't including any lines of code in your code block, which is causing `lines` [here](https://github.com/wbaldoumas/markdown-colorcode/blob/main/src/Markdown.ColorCode/ColorCodeBlockRenderer.cs#L71) to be `null`, which is immediately followed up by that null reference exception you are hitting.

My expectation would have been that this value would be an empty array rather than `null`, but it seems like Markdig is setting it to `null` when no lines of code are included and I will have to handle for that case.

**Comment by wbaldoumas** [comment] 2023-05-25 01:02
@ogchrislem https://github.com/wbaldoumas/markdown-colorcode/pull/89 currently addresses this. 

Feel free to give it a try by installing preview version `1.0.4-preview-2`. Let me know how that works and I will work to get a new release out when I can.

**Comment by wbaldoumas** [comment] 2023-05-26 02:10
@ogchrislem version `1.0.4` should be published and available for use. Closing this issue, since it seems like this resolved what you were seeing. 

Thank you for your contribution!

**Closed by wbaldoumas** 2023-05-26 02:10 UTC
Labels: bug, help wanted, good first issue, needs: triage
